### ISSUE TITLE
Very large lmdb database is slow.

### ISSUE THREAD

**Issue by wantsjean** [jinyu121/video2frame#4]
I use 2T HDD,  the LMDB database's size is 800G and my server has 100G RAM, the training is very fast at first, but then slow down, and I found that the memory cache/buffer is full. How to solve the problem?

**Comment by jinyu121** [comment]
Well, I have not tried such a large data set. :(

But I think you can split the lmdb file into several smaller files. May [this repo](https://github.com/forwchen/vid2frame) and [this section](https://github.com/forwchen/vid2frame#1-split-video-dataset-into-multiple-if-necessary-splits-with-split_video_datasetpy) gives you some inspirations.

**Comment by wantsjean** [comment]
@jinyu121 Everything's going well when I mount the data on SSD, thanks
